### ISSUE TITLE
Environment_DarkenWater is always set to 1 every time you load a map.. somtimes?

### ISSUE THREAD

**Issue by WolfeStrider** [JonahSoldier/Gmod-Light-Environment-Editor#4]
Sometimes it will be set to 1 and you'll need to toggle it on and off if you want it to be set properly back to 0, and sometimes that doesn't work and the water stays dark

**Comment by JonahSoldier** [comment]
It's meant to be set to 1 by default. I changed it to be on by default after I switched it to editing the water fog directly rather than just trying to hide it with a black square, with the reason being that it shouldn't have any effect unless you've changed the ambient light. I'd be more concerned if it sometimes (or often) _wasn't_ set to 1, because then something actually is wrong.

I'm pretty sure the second issue mentioned happened because of the same reasons as the other bug with Water Darkening. It _should_ be fixed, but tell me if it isn't.

**Comment by WolfeStrider** [comment]
Both this bug and #5 seem to be fixed now you can now close these issues at your discretion. Although I suggest by default Environment_DarkenWater should be set to 0 and then the player applies all the fixes they prefer afterward just like the rest of the cvars

**Comment by JonahSoldier** [comment]
I prefer keeping it enabled by default, as it doesn't (or at least shouldn't) have any negative side-effects. The fix for Dynamic Lights/Projected Textures is on by default for the same reason. It's more convenient for people who aren't familiar with what everything does yet this way, and I don't think un-checking the box is too much extra work for anyone who does want to disable it.
